### PR TITLE
examples: read_devices: Improve usage

### PR DESCRIPTION
**Pull request by patrickelectric**
- Use base 16 as arguments
- Panic if something goes wrong when opening the device

### CODE REVIEW

**Comment by a1ien** [comment]
Hi. Thanks for PR. I welcome these changes. But maybe better allow both 10 base and 16 base. And distinguished them by 0x before the number?

**Comment by patrickelectric** [comment]
> Hi. Thanks for PR. I welcome these changes. But maybe better allow both 10 base and 16 base. And distinguished them by 0x before the number?

that's a possibility, but I have personally never seen any program use base 10 for pid and vid besides this example.

**Comment by patrickelectric** [comment]
@a1ien done.

**Comment by a1ien** [comment]
LGTM. Thanks

**Pull request merged**
