### PR TITLE
Do not use unsafe in `read_device` example

### PR DESCRIPTION
**Pull request by rossmacarthur**

### CODE REVIEW

**Comment by a1ien** [comment]
Why do you want these changes? This example show how to use buffer efficiently, without zeroing.

**Comment by rossmacarthur** [comment]
@a1ien I just thought it was unsightly. When I looked at the example I had to stop to double check what the unsafe code was doing and it distracted from the example somewhat. Plus at this size buffer the performance increase is probably in nanoseconds.

**Comment by a1ien** [comment]
I think it’s better to replace the vector to array.

**Comment by rossmacarthur** [comment]
Yeah, that's possible. Only issue is you can't `Debug` print array bigger than 32 bytes. So we would have to implement the output.

**Comment by a1ien** [comment]
We can `Debug` print as slice

**Comment by a1ien** [comment]
LGTM. Thanks.

**Comment by brandonros** [comment]
Can you update this to not hardcode `256` bytes but instead use something like `in_endpoint.max_packet_size() as usize`?

**Comment by rossmacarthur** [comment]
@brandonros that's not a problem, but I don't think we can use an array then? We would have to use a `Vec` again.

See https://github.com/a1ien/rusb/compare/master...rossmacarthur:ft/use-endpoint-packet-size

**Pull request merged**
