### PR TITLE
Add Context::interrupt_handle_events()

### PR DESCRIPTION
**Pull request by elmarco**
Depends on https://github.com/a1ien/rusb/pull/97

### CODE REVIEW

**Comment by a1ien** [comment]
Can you add some documentation.

**Comment by a1ien** [comment]
`#[doc(alias = "libusb_interrupt_event_handler")]` usable thing.

About warning. You can leave it as it was. I want rewrite hotplug https://github.com/a1ien/rusb/tree/registerHotplug and rewrite doc

**Comment by elmarco** [comment]
ok
If you don't mind to take the warn fix in the mean time, it clears cargo doc output!

**Comment by elmarco** [comment]
@a1ien is that ok? thanks

**Comment by a1ien** [comment]
Thanks

**Pull request merged**
