### PR TITLE
Add vendored feature to force libusb-1.0 build

### PR DESCRIPTION
**Pull request by Jonathas-Conceicao**
This is related to: https://github.com/a1ien/libusb1-sys/pull/13

### CODE REVIEW

**Comment by otavio** [comment]
@a1ien this PR is awaiting for the release of `libusb1-sys`. Any ETA for it?

**Comment by a1ien** [comment]
13.01. I'am away from PC.

**Comment by otavio** [comment]
> 13.01. I'am away from PC.

Good; thanks for your prompt reply.

**Comment by otavio** [comment]
Can you do a new release?

**Comment by a1ien** [comment]
Done

**Pull request merged**
