### PR TITLE
Add get_parent

### PR DESCRIPTION
**Pull request by serpilliere**
Add the `get_parent` API from libusb-sys `libusb_get_parent`

### CODE REVIEW

**Comment by a1ien** [comment]
How we can ensure that it's safe? In libusb say 
>You should issue a libusb_get_device_list() before calling this function and make sure that you only access the parent before issuing libusb_free_device_list(). The reason is that libusb currently does not maintain a permanent list of device instances, and therefore can only guarantee that parents are fully instantiated within a libusb_get_device_list() - libusb_free_device_list() block.

**Comment by a1ien** [comment]
Also we must call `libusb_ref_device(device.as_ptr());`

**Comment by serpilliere** [comment]
Oh! Right. I have totally failed in reading the doc.
I will review this.

**Comment by serpilliere** [comment]
As you pointed out, it seems that the `libusb` library relies on the fact that the user should respect the calling order of those function:
- `libusb_get_device_list()`
- `libusb_get_parent(...)`
- `libusb_free_device_list(...)` 

Another point is that we must not access a device after having 'unref' it.

So, we could "rely" on the user behavior, which means the code may be unsafe in case of bad API usage.
Another solution may be to add a `get_parent` function to the `DeviceList` (or the `Devices`). 
Something like:
```rust
impl<T: UsbContext> DeviceList<T> {
    pub fn get_parent(&self, device: &Device) -> Device {
         ...
   }
...
}
```
The good point here is that the user is *forced* to call `DeviceList` before calling `get_parent`.
But I see another tricky case:
- the user get a Device
- the user gets a `DeviceList`
- the user calls the `device_list.get_parent` with the device previously retrieved.

I don't see a case where we won't have a hole in the net and don't have to rely on the user behavior :sad:

Another interesting point is how the `parent` is used in the `libusb`. The `libusb_get_parent` accesses the parent with https://github.com/libusb/libusb/blob/eee6998395184d87bd8e9c07ce2637caed1207f4/libusb/core.c#L996:
```C
DEFAULT_VISIBILITY
libusb_device * LIBUSB_CALL libusb_get_parent(libusb_device *dev)
{
	return dev->parent_dev;
}
```

But in https://github.com/libusb/libusb/blob/eee6998395184d87bd8e9c07ce2637caed1207f4/libusb/core.c#L951 we have:
```C
int API_EXPORTED libusb_get_port_numbers(libusb_device *dev,
	uint8_t *port_numbers, int port_numbers_len)
{
	int i = port_numbers_len;
	struct libusb_context *ctx = DEVICE_CTX(dev);

	if (port_numbers_len <= 0)
		return LIBUSB_ERROR_INVALID_PARAM;

	// HCDs can be listed as devices with port #0
	while((dev) && (dev->port_number != 0)) {
		if (--i < 0) {
			usbi_warn(ctx, "port numbers array is too small");
			return LIBUSB_ERROR_OVERFLOW;
		}
		port_numbers[i] = dev->port_number;
		dev = dev->parent_dev;
	}
	if (i < port_numbers_len)
		memmove(port_numbers, &port_numbers[i], port_numbers_len - i);
	return port_numbers_len - i;
}
```
As you can see, the libusb is using the `parent_dev` without explicitly saying in the documentation that we must call `libusb_get_device_list` before using it. So 

What about you: Is the second solution seems acceptable for you or have you something else in mind ?
By the way, do you mind if I add the `get_port_numbers` in the PR or if I add this function in another PR ?

**Comment by a1ien** [comment]
I ask in libusb about function and it's ok call outside libusb_get_device_list() - libusb_free_device_list() block.
Can you add fix as I ask in comment
> Also we must call libusb_ref_device(device.as_ptr()); Or call Device::from_libusb

`Device::from_libusb` better

**Comment by serpilliere** [comment]
I have added the `from_libsub`, but in the map closure.
Is it ok for you ? (I have doubt on the location)

**Comment by a1ien** [comment]
LGTM. Thanks.

**Comment by serpilliere** [comment]
Thank you @a1ien

**Pull request merged**
