### PR TITLE
Some rework aiming for 0.6 inclusion

### PR DESCRIPTION
**Pull request by otavio**
As 0.6 release seems like obvious, I took a look at the code and did minor rework so those changes could go in, if approved, on the same release.

Take a look at the proposed changes.

### CODE REVIEW

**Comment by a1ien** [comment]
I would not want to add additional dependencies. Can we go without derive_more

**Comment by otavio** [comment]
> I would not want to add additional dependencies. Can we go without derive_more

We can, for sure. If desired, I can drop it from the branch.

As a reason to keep it is that `derive_more` only depends on `syn` and it is a very common dependency. Also, as I did enable just the macros we currently use.

I personally prefer to reduce the amount of code to maintain and to prefer commonly used dependencies, so we 'reuse' the previously built dependencies. In this scenario, the built time would be the same.

So please, what solution do you prefer?

**Comment by pheki** [comment]
Just tested it, and on my machine (which is kinda slow) it adds 10s to the first debug build and about 50s in first release build when adding derive_more directly for my crate (its not on my dependency tree).

Without `derive_more`:
```
$ cargo clean
$ cargo build
Finished dev [unoptimized + debuginfo] target(s) in 58.27s
$ cargo clean --release
$ cargo build --release
Finished release [optimized] target(s) in 2m 36s
```
With `derive_more = "0.99"`:
```
$ cargo clean
$ cargo build
Finished dev [unoptimized + debuginfo] target(s) in 1m 07s
$ cargo clean --release
$ cargo build --release
Finished release [optimized] target(s) in 3m 29s
```

For reference:
```
[dependencies]
rusb = "0.5"
structopt = "0.3"
crossbeam-channel = "0.4"
lazy_static = "1.4"
# derive_more = "0.99"
```

### Just my opinion

While I agree that adding dependencies is not necessarily bad, specially "shared" ones, I think that the maintenance burden (e.g. updating the library when 0.100 comes out) isn't worth the trouble in this case.

**Comment by otavio** [comment]
Already. I removed derive_more use. Please check it again @pheki @a1ien.

**Comment by a1ien** [comment]
LGTM. I will do release on monday.

**Pull request merged**
