### PR TITLE
Demonstrate using new libusb functionality

### PR DESCRIPTION
**Pull request by avantgardnerio**
Add an example Android app to show what the new functionality in the previous PR supports.

works via android

### CODE REVIEW

**Comment by avantgardnerio** [comment]
I manually tested this on Android after the rebase. I spent some time over the weekend and believe it's possible to add tests on an Android emulator in travis-ci as well.

**Comment by a1ien** [comment]
I don't really like the idea of adding android code to the repository. Maybe put this example in a separate repository. And add a link to it in the documentation

**Comment by avantgardnerio** [comment]
> separate

No problem, I'll close this PR and make a new one with the link. 

Quick favor though: would you be able to publish the crate for 0.6.4? I'd love to replace the submodule in our repo with a crate reference.

Thanks again!

**Comment by a1ien** [comment]
> publish the crate for 0.6.4

Done

**Pull request closed without merging**
